.multiSelectOption {
	font-size: 15px;
	padding: 5px;
}
#multiSelectBox > option {
	font-size: 15px;
	padding: 5px;
}
.multiSelectHeader {
	line-height: 200% !important;
}
.disabledAnchor {
	pointer-events: none;
	color: #D8DDE6 !important;
}
.buttons-div {
	margin: auto 0;
}
.buttons-div * {
	font-family: initial;
}
.classicButton {
	width: 1.8rem;
    text-align: center;
    padding: 4px !important;
    margin: 3px 5px !important;
}